theme = "myTokyoNight"

[editor]
line-number = "absolute"
bufferline = "always"
color-modes = true
cursorline = true
auto-format = false
true-color = true

[editor.indent-guides]
render = true
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator"]
right = ["diagnostics","position", "file-encoding"] 
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"    

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.auto-pairs]
'`' = '`'
"'" = "'"
'"' = '"'
'(' = ')'
'{' = '}'
'[' = ']'

[editor.soft-wrap]
enable = false
max-wrap = 25 
max-indent-retain = 0
wrap-indicator = ""

[editor.gutters]
layout = ["diff","diagnostics", "line-numbers", "spacer"]

[keys.select]
y = [':clipboard-yank', "collapse_selection"]

[keys.normal]
y = ':clipboard-yank'
p = ':clipboard-paste-before'


# Macros
# Command On Windows
# [keys.insert.C-m]
# r = ":insert-output type C:\\Users\\Admin\\AppData\\Roaming\\helix\\macros\\rfc.jsx"
# h = ":insert-output type C:\\Users\\Admin\\AppData\\Roaming\\helix\\macros\\html5.html"
# v = ":insert-output type C:\\Users\\Admin\\AppData\\Roaming\\helix\\macros\\sfc.vue"

# Macros
# Command On Linux
[keys.insert.C-m]
r = [":insert-output cat ~/dotfiles/helix/snippets/rfc.jsx", "normal_mode"]
h = [":insert-output cat ~/dotfiles/helix/snippets/html5.html", "normal_mode"]
v = [":insert-output cat ~/dotfiles/helix/snippets/sfc.vue", "normal_mode"]

[editor.lsp]
display-inlay-hints = true
