theme = "tokyonight_moon"

[editor]
line-number = "relative"
bufferline = "always"
color-modes = true
cursorline = true
auto-format = false
true-color = true
idle-timeout = 0

[editor.indent-guides]
render = true
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator"]
right = ["diagnostics","position", "file-encoding"] 
mode.normal = " NOR" 
mode.insert = " INS" 
mode.select = " SEL"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.auto-pairs]
'`' = '`'
"'" = "'"
'"' = '"'
'(' = ')'
'{' = '}'
'[' = ']'

# [editor.soft-wrap]
# enable = false
# max-wrap = 25 
# max-indent-retain = 0
# wrap-indicator = ""

[editor.gutters]
layout = ["diff","diagnostics", "line-numbers", "spacer"]

[keys.normal]
p = ':clipboard-paste-before'
D = [':clipboard-yank', "delete_selection_noyank"]
"space" = { "c" = ':buffer-close', "n" = ":new"}
"+" = { "o" = ":pipe-to xargs open" } 

"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

"tab" = 'goto_next_buffer'
"S-tab" = 'goto_previous_buffer'

0 = "goto_line_start"
"$" = 'goto_line_end'
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"

C-h = "select_prev_sibling"
C-j = "shrink_selection"
C-k = "expand_selection"
C-l = "select_next_sibling"

C-r = ":config-reload"
C-o = ":config-open"

# Disable
g = { e = "no_op", l = "no_op", h = "no_op", n = "no_op", p = "no_op"}

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
t = ["extend_till_char"]
s = ["surround_delete"]
i = ["select_textobject_inner"]
a = ["select_textobject_around"]
j = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
down = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
k = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
up = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
G = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
g = { g = ["select_mode", "extend_to_line_bounds", "goto_file_start", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"] }

[keys.normal.y]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]
j = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
down = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]
k = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "collapse_selection", "normal_mode"]

[keys.select]
y = [':clipboard-yank', "collapse_selection", "normal_mode"]
D = [':clipboard-yank', "delete_selection_noyank", "collapse_selection", "normal_mode"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"

[keys.insert]
C-h = "move_char_left"
C-l = "move_char_right"
C-s = ":write" 

# Snippets
[keys.insert.C-n]
r = [":insert-output cat ~/dotfiles/helix/snippets/rfc.jsx", "normal_mode"]
h = [":insert-output cat ~/dotfiles/helix/snippets/html5.html", "normal_mode"]
v = [":insert-output cat ~/dotfiles/helix/snippets/sfc.vue", "normal_mode"]
d = [":insert-output echo $(date +'%Y-%m-%d')", "normal_mode"]

# [editor.lsp]
# display-inlay-hints = true
