"comment" = { fg = "comment", modifiers = ["italic"] }
"constant" = { fg = "orange" }
"constant.character.escape" = { fg = "magenta" }
"function" = { fg = "blue", modifiers = ["italic"] }
"function.macro" = { fg = "cyan" }
"keyword" = { fg = "cyan", modifiers = ["italic"] }
"keyword.control" = { fg = "magenta" }
"keyword.control.import" = { fg = "cyan" }
"keyword.control.return" = { fg = "purple", modifiers = ["italic"] }
"keyword.directive" = { fg = "cyan" }
"keyword.operator" = { fg = "turquoise" }
"keyword.function" = { fg = "magenta", modifiers = ["italic"] }
"operator" = { fg = "turquoise" }
"punctuation" = { fg = "turquoise" }
"string" = { fg = "light-green" }
"string.regexp" = { fg = "light-blue" }
"tag" = { fg = "red" }
"type" = { fg = "aqua" }
"type.builtin" = { fg = "aqua" }
"type.enum.variant" = { fg = "orange" }
label = { fg = "blue" }
"namespace" = { fg = "blue" }
"variable" = { fg = "white" }
"variable.builtin" = { fg = "red" }
"variable.other.member" = { fg = "green" }
"variable.parameter" = { fg = "yellow", modifiers = ["italic"] }
"constructor" = { fg = "red" }
"attribute" = { fg = "magenta" }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "orange" }
"diff.minus" = { fg = "red" }

# "ui.background" = {  fg = "foreground", bg = "background" } 
# transparent
"ui.background" = { fg = "foreground" } 
"ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "orange", modifiers = ["bold"] }
"ui.cursor.primary" = { modifiers = ["reversed"] }
"ui.cursorline.primary" = { bg = "background_menu" }
"ui.help" = { fg = "foreground", bg = "background_menu" }
"ui.linenr" = { fg = "comment" }
"ui.linenr.selected" = { fg = "foreground" }
"ui.menu" = { fg = "foreground", bg = "background_menu" }
"ui.menu.selected" = { bg = "background_highlight" }
"ui.popup" = { fg = "foreground", bg = "background_menu" }
"ui.selection" = { bg = "background_highlight" }
"ui.selection.primary" = { bg = "background_highlight" }
"ui.statusline" = { fg = "foreground", bg = "background" }
"ui.statusline.inactive" = { fg = "foreground_gutter", bg = "background_menu" }
"ui.statusline.normal" = { fg = "background" , bg = "blue", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "background", bg = "orange", modifiers = ["bold"]} 
"ui.statusline.select" = { fg = "background", bg = "light-cyan", modifiers = ["bold"]}
"ui.bufferline" = { fg = "comment", bg = "background" }
"ui.bufferline.active" = { fg = "background", bg = "blue" }

"ui.text" = { fg = "foreground" }
"ui.text.focus" = { fg = "cyan" } 
"ui.virtual.ruler" = { bg = "foreground_gutter" }
"ui.virtual.whitespace" = { fg = "foreground_gutter" }
"ui.virtual.inlay-hint" = { bg = "background_inlay", fg = "comment", modifiers = ["italic"] }
"ui.window" = { fg = "black" }

"error" = { fg = "red" }
"warning" = { fg = "yellow" }
"info" = { fg = "blue" }
"hint" = { fg = "teal" }
"diagnostic.error" = { underline = { style = "curl", color = "red" } }
"diagnostic.warning" = { underline = { style = "curl", color = "yellow" } }
"diagnostic.info" = { underline = { style = "curl", color = "blue" } }
"diagnostic.hint" = { underline = { style = "curl", color = "teal" } }
"special" = { fg = "orange" }

"markup.heading.marker" = { fg = "white", modifiers = ["italic"]}
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.3" = { fg = "light-green", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "turquoise", modifiers = ["bold"] }
"markup.list" = { fg = "cyan" }
"markup.list.numbered" = { fg = "orange" }
"markup.list.unchecked" = { fg = "white", bg = "comment" }
"markup.list.checked" = { fg = "background_menu", bg = "light-green" }
"markup.bold" = { fg = "green", modifiers = ["bold"] }
"markup.italic" = { fg = "foreground", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = { fg = "blue", underline = { style = "line" } }
"markup.link.label" = { fg = "cyan" }
"markup.link.text" = { fg = "cyan" }
"markup.link.url" = { fg = "green", underline = { style = "line" } }
"markup.quote" = { fg = "yellow", bg = "background_menu", modifiers = ["italic"] }
"markup.raw" = { fg = "red", bg = "background_menu"}

[palette]
red = "#f7768e"
orange = "#ff9e64"
yellow = "#e0af68"
light-green = "#9ece6a"
green = "#73daca"
turquoise = "#89ddff"
light-cyan = "#b4f9f8"
aqua = "#2ac3de"
teal = "#1abc9c"
cyan = "#7dcfff"
blue = "#7aa2f7" 
purple = "#9d7cd8"
magenta = "#bb9af7"
white = "#c0caf5"
light-gray = "#9aa5ce"
parameters = "#cfc9c2"
comment = "#565f89"
black = "#414868"


foreground = "#a9b1d6"
foreground_highlight = "#c0caf5"
foreground_gutter = "#363b54"
background = "#24283b"
background_highlight = "#434c69"
background_menu = "#1a1b26"
background_inlay = "#313952"

# OLD VALUE
# background_highlight = "#30374b"
# background_menu = "#282836"
# background_menu = "#16161e"
# "ui.linenr" = { fg = "foreground_gutter" }
